### ISSUE TITLE
Docker compose?

### ISSUE THREAD

**Issue by ajanini** [bloiseleo/MusicBox#1]
Bom dia Leonardo, tudo bem?

Você pode fornecer seu YAML e dockerfile (se for o caso) do projeto, por favor?

Obrigado

**Comment by bloiseleo** [comment]
Além disso, também não há um dockerfile, pois todas as configurações estão
no start.sh passadas através de linha de comando

Em seg., 19 de jun. de 2023 09:02, Leonardo Bloise <
***@***.***> escreveu:

**Comment by ajanini** [comment]
Digamos que eu não tenha em meu ambiente de desenvolvimento o PHP ou o Postgres, por exemplo.
Como eu devo fazer para subir os contêineres necessários?

**Comment by bloiseleo** [comment]
No caso, o Postgres não é necessário de qualquer forma, visto que ele está
sendo executado dentro de um container docker e você só precisa do docker.

No caso do PHP, nesse caso, para rodar sem o ambiente PHP, precisaria de um
docker compose para orquestrar 2 containers com duas imagens: uma do
Postgres e uma do PHP com apache.

Para rodar sem o docker-compose, será necessário instalar o PHP e o
composer.

Em seg., 19 de jun. de 2023 09:14, Alexandre R. Janini <
***@***.***> escreveu:

**Comment by bloiseleo** [comment]
Docker-compose adicionado.

Agora, você pode subir o projeto somente com docker-compose up

**Comment by ajanini** [comment]
Muito bom. Contêineres construídos!

Mas estou recebendo erro ao acessar http://localhost:8080/graphiql (tive que usar a porta `8080` porque é a que está exposta no YAML):

```
Error: Introspection must provide input type for arguments, but received: lyric.
    at exports.default (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:611828)
    at getInputType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:781671)
    at buildInputValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:785985)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:612879
    at Array.reduce (<anonymous>)
    at exports.default (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:612829)
    at buildInputValueDefMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:785838)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:785703
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js:1:612879
    at Array.reduce (<anonymous>)
```

<img width="1275" alt="Captura de Tela 2023-06-19 às 21 19 21" src="https://github.com/bloiseleo/MusicBox/assets/3225794/b3078bd4-2263-4ca1-b238-5f30a7b65578">

**Comment by bloiseleo** [comment]
Obrigado por pontuar o problema. Irei averiguar essa questão. Entretanto, vejo que não é impeditivo para a realização de operações.

![image](https://github.com/bloiseleo/MusicBox/assets/105981050/c0f5a6af-4e70-41bc-ae49-c4b0b1c4de42)

**Comment by bloiseleo** [comment]
Recebi o comunicação de que não fui selecionado. Agradeço pelo tempo disponibilizado.
